apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
